/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-error-container": "#93000a",
        "tertiary": "#574fbe",
        "inverse-surface": "#2f3132",
        "surface-bright": "#f9f9fb",
        "secondary-fixed-dim": "#c4c1fb",
        "on-secondary-fixed": "#171445",
        "on-primary-fixed": "#3a0031",
        "error-container": "#ffdad6",
        "surface-tint": "#943e80",
        "surface-container-low": "#f3f3f5",
        "on-tertiary-fixed": "#130068",
        "primary-container": "#ff99e2",
        "tertiary-container": "#b8b3ff",
        "surface-variant": "#e2e2e4",
        "on-error": "#ffffff",
        "on-surface-variant": "#51434b",
        "on-secondary": "#ffffff",
        "surface-container": "#eeeef0",
        "on-secondary-container": "#514f82",
        "surface-container-lowest": "#ffffff",
        "on-tertiary": "#ffffff",
        "background": "#F2F2F2",
        "surface": "#F2F2F2",
        "surface-dim": "#d9dadc",
        "secondary": "#5b598d",
        "primary-fixed-dim": "#ffade5",
        "on-background": "#1a1c1d",
        "outline": "#84727c",
        "on-surface": "#1a1c1d",
        "inverse-primary": "#ffade5",
        "outline-variant": "#d6c1cc",
        "on-primary-fixed-variant": "#782567",
        "secondary-fixed": "#e3dfff",
        "on-primary": "#ffffff",
        "tertiary-fixed-dim": "#c4c0ff",
        "inverse-on-surface": "#f0f0f2",
        "error": "#ba1a1a",
        "secondary-container": "#c6c3fe",
        "primary-fixed": "#ffd7ef",
        "on-tertiary-fixed-variant": "#3e34a5",
        "surface-container-high": "#e8e8ea",
        "primary": "#943e80",
        "on-primary-container": "#7c296b",
        "surface-container-highest": "#e2e2e4",
        "on-secondary-fixed-variant": "#434173",
        "on-tertiary-container": "#4339a9",
        "tertiary-fixed": "#e3dfff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "sm": "12px",
        "xs": "4px",
        "margin-desktop": "64px",
        "md": "24px",
        "margin-mobile": "16px",
        "xl": "80px",
        "lg": "48px",
        "gutter": "20px",
        "base": "8px"
      },
      fontFamily: {
        "headline-md": ["Plus Jakarta Sans"],
        "body-md": ["Inter"],
        "label-sm": ["Plus Jakarta Sans"],
        "body-sm": ["Inter"],
        "label-md": ["Plus Jakarta Sans"],
        "headline-xl": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "body-lg": ["Inter"]
      },
      fontSize: {
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "label-sm": ["12px", {"lineHeight": "14px", "fontWeight": "600"}],
        "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "label-md": ["14px", {"lineHeight": "16px", "letterSpacing": "0.01em", "fontWeight": "600"}],
        "headline-xl": ["40px", {"lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
